DROP DATABASE IF EXISTS test;
DROP ROLE IF EXISTS test_user;
CREATE DATABASE test;
CREATE ROLE test_user LOGIN PASSWORD '123123';
GRANT ALL PRIVILEGES ON DATABASE test TO test_user;
\ c test;
ALTER ROLE test_user
SET search_path = test;