DROP DATABASE IF EXISTS nest;
DROP ROLE IF EXISTS nest_user;
CREATE DATABASE nest;
CREATE ROLE nest_user LOGIN PASSWORD '123123';
GRANT ALL PRIVILEGES ON DATABASE nest TO nest_user;
\ c nest;
GRANT USAGE,
  CREATE ON SCHEMA public TO nest_user;