@prefix = http://localhost:9876/api
{{
  const session = 'xxx'
  exports.defaultHeaders = {
    'Content-Type': 'application/json',
    'Cookie': `session=${session}`
  };
}}

### user.register
# 用户测试
@name = {{$random.alphabetic(10)}}
POST {{prefix}}/user/register
...defaultHeaders
{
  "name": "{{name}}",
  "email": "{{name}}@gmail.com",
  "password": "123456",
  "code": "0000"
}

### user.login.success
# 用户登录
POST {{prefix}}/user/login
...defaultHeaders
{
  "email": "VhksVjjgCD@gmail.com",
  "password": "123456",
  "code": "0000"
}

### user.logout.success
# 用户登出
POST {{prefix}}/user/logout
...defaultHeaders
{}

### health.get
# 健康检查
GET {{prefix}}/health
...defaultHeaders
