@prefix = http://localhost:9872/api
{{
  exports.defaultHeaders = {
  };
}}

### book.create
# 创建图书
POST {{prefix}}/book
Content-Type: application/json

{
  "title": "深入理解计算机系统",
  "author": "Randal E. Bryant",
  "publisher": "机械工业出版社",
  "isbn": "978-7-111-54493-7",
  "description": "从程序员的视角详细阐述计算机系统的本质概念",
  "publishDate": "2016-11-01",
  "pages": 736
}

### book.list
# 获取图书列表

GET {{prefix}}/book?limit=10&offset=0

### book.search.name
# 搜索图书（按标题）
GET {{prefix}}/book?title=深入理解&limit=10&offset=0

### book.search.author
# 搜索图书（按作者）
GET {{prefix}}/book?author=Randal&limit=10&offset=0

### book.get
# 获取单本图书详情
@id = 119412990364618752
GET {{prefix}}/book/{{id}}

### book.update
# 更新图书信息
@id = 119412990364618752
PUT {{prefix}}/book/{{id}}

{
  "title": "深入理解计算机系统（原书第3版）",
  "description": "从程序员的视角详细阐述计算机系统的本质概念，更新版"
}

### book.delete
# 删除图书
@id = 123456
DELETE {{prefix}}/book/{{id}}

### user.register
# 用户测试
@name = {{$random.alphabetic(10)}}
POST {{prefix}}/user/register
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{name}}@gmail.com",
  "password": "123456",
  "code": "0000"
}

### user.login.success
# 用户登录
POST {{prefix}}/user/login
Content-Type: application/json
{
  "email": "VhksVjjgCD@gmail.com",
  "password": "123456",
  "code": "0000"
}


### user.logout.success
# 用户登出
POST {{prefix}}/user/logout
Content-Type: application/json
{}


### health.get
# 健康检查
GET {{prefix}}/health
