services:
  postgres:
    container_name: nest-app-postgres
    image: docker.io/library/postgres:18.3-alpine
    restart: always
    labels:
      app: nest-app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nest-app.pass
    ports:
      - 0.0.0.0:33301:5432
    volumes:
      - /opt/nest-app/postgres:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "127.0.0.1",
          "-p",
          "5432",
          "-q",
          "-U",
          "postgres",
        ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
