services:
  redis:
    # replace password with your own
    command: redis-server /etc/redis/redis.conf --appendonly yes --requirepass "${CURRENT_APP}.pass"
    container_name: ${CURRENT_APP}-redis
    image: redis:8.6.1
    labels:
      app: ${CURRENT_APP}
    ports:
      - 0.0.0.0:60101:6379
    restart: always
    volumes:
      - /opt/${CURRENT_APP}/redis/data:/data
      - /opt/${CURRENT_APP}/redis/conf/redis.conf:/etc/redis/redis.conf
      - /opt/${CURRENT_APP}/redis/logs:/logs
  postgres:
    container_name: ${CURRENT_APP}-postgres
    image: postgres:18.3-alpine
    restart: always
    labels:
      app: ${CURRENT_APP}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${CURRENT_APP}.pass
    ports:
      - 0.0.0.0:60102:5432
    volumes:
      - /opt/${CURRENT_APP}/postgres:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "127.0.0.1",
          "-p",
          "5432",
          "-q",
          "-U",
          "postgres",
        ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
