-- Replace password with your own password
CREATE ROLE nest_db WITH LOGIN PASSWORD '123123';

CREATE DATABASE nest_db
  OWNER nest_db
  ENCODING 'UTF8'
  TEMPLATE template0;

REVOKE ALL ON DATABASE nest_db FROM PUBLIC;
REVOKE CONNECT ON DATABASE nest_db FROM PUBLIC;

GRANT CONNECT ON DATABASE nest_db TO nest_db;
GRANT USAGE, CREATE ON SCHEMA public TO nest_db;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nest_db;